format code
curbox-app/curbox-android pull request #1
Opened 2024-05-08 14:23 UTC by appt2

hi me formating all xml and java and adding lastversion androidx and material

2024-05-08 14:33 UTC, RealNethical commented
Damn I really appreciate it. I was looking for someone to help me do it . Thanks a lot....

2024-05-08 14:42 UTC, merged

2024-05-08 14:50 UTC, appt2 commented
> Damn I really appreciate it. I was looking for someone to help me do it . Thanks a lot....

Please, I saw that your codes are messed up, I arranged them, and you were using old libraries, so this option is not recommended, at least gr is recommended version 8.2.2

2024-05-09 01:50 UTC, remaker17 requested changes

2024-05-09 01:50 UTC, remaker17 commented on app/build.gradle
> +    implementation 'com.squareup.okhttp3:okhttp:5.0.0-alpha.12'
where proper formatting?

2024-05-09 01:50 UTC, remaker17 commented on app/src/main/AndroidManifest.xml
>  <?xml version="1.0" encoding="utf-8"?>
same here

2024-05-09 01:50 UTC, remaker17 commented on app/src/main/java/nethical/digipaws/Constants.java
>  package nethical.digipaws;
why are you using 2 space tab instead of 4?
you are already using 4 space tab in some files.

2024-05-09 01:53 UTC, remaker17 requested changes
Please do not make unwanted changes in next time.

2024-05-09 01:53 UTC, remaker17 commented on .github/workflows/runer.yml
> +name: Android CI
Why are you adding unwanted changes?
Pull request title: **Format code**

2024-05-09 01:53 UTC, remaker17 commented on app/build.gradle
> +    compileSdk 34
Same here

2024-05-09 01:53 UTC, remaker17 commented on app/build.gradle
> +        targetCompatibility JavaVersion.VERSION_17
Same here

2024-05-09 02:06 UTC, RealNethical commented
💀💀

2024-05-09 02:08 UTC, RealNethical commented
I have reset all changes. Please fix and reopen another pr